TulevaEE/onboarding-client

package.json
scripts/start.js
yarn.lock

For example, main.js goes from 300kb to 80kb.

Add gzip compression to node static server

---

src/steps/confirmMandate/ConfirmMandate.js
src/steps/confirmMandate/ConfirmMandate.spec.js

Since the user can create an arbitrary amount of selections essentially, we still want the mandate to be simple.

Aggregate selections before showing them

---

README.md
package.json
scripts/start.js
src/common/api.js
src/common/http.js
yarn.lock

CORS is too flaky for our use cases, plus has a tangible performance hit, since we practically never do a "simple request". This removes CORS from prod and replaces it with a proxy endpoint in the static server.

Route requests through a proxy instead of using CORS in production

---

src/login/LoginPage.js
src/login/LoginPage.scss

Layout on smaller screens breaks because of the width of FB widget:
This is also reproducable on any desktop browser by resizing the window basically as narrow as it gets.
This PR adds a quick fix for hiding overflow on that widget to avoid those effects.

Hide facebook widget's overflow to avoid broken layout

---

src/entries/components/login/LoginPage.js
src/entries/components/login/LoginPage.spec.js
src/entries/components/login/loginForm/LoginForm.js
src/entries/components/login/loginForm/LoginForm.spec.js
src/entries/components/thirdPillar/actions.js
src/entries/components/thirdPillar/actions.spec.js
src/entries/components/thirdPillar/constants.js
src/entries/components/thirdPillar/index.js
src/entries/components/thirdPillar/initialState.js
src/entries/components/thirdPillar/reducer.js
src/entries/components/thirdPillar/reducer.spec.js
src/entries/components/translations/translations.en.json
src/entries/components/translations/translations.et.json
src/entries/onboarding.js

When applied:
* `monthlyThirdPillarContribution` and`exchangeExistingThirdPillarUnits` query params will be stored in state under `thirdPillar`.
* when `monthlyThirdPillarContribution` is in state on the login page, 3rd pillar specific headings will be shown (also depending on `exchangeExistingThirdPillarUnits`)

Show 3rd pillar headings on login page when monthlyThirdPillarContribution and exchangeExistingThirdPillarUnits in query parameters

---

src/entries/components/flows/thirdPillar/ConfirmThirdPillarMandate/ConfirmThirdPillarMandate.js
src/entries/components/flows/thirdPillar/ConfirmThirdPillarMandate/ConfirmThirdPillarMandate.spec.js
src/entries/components/flows/thirdPillar/ThirdPillarSetup/ThirdPillarSetup.js
src/entries/components/flows/thirdPillar/ThirdPillarSetup/ThirdPillarSetup.spec.js
src/entries/components/thirdPillar/initialState.js
src/entries/components/thirdPillar/reducer.js
src/entries/components/thirdPillar/reducer.spec.js

Previously, we would show the exchange existing units checkbox on the first step of third pillar flow even when the only third pillar source fund is the same as the target fund (currently LHV Index Plus). This PR fixes that.

Show exchange existing units choice only when exchangeable funds exist

---

src/entries/components/account/AccountStatement/AccountStatement.js
src/entries/components/account/AccountStatement/AccountStatement.spec.js
src/entries/components/account/MemberCapital/MemberCapital.js
src/entries/components/account/MemberCapital/MemberCapital.spec.js
src/entries/components/common/Euro/Euro.js
src/entries/components/common/Euro/index.js
src/entries/components/flows/secondPillar/selectSources/pensionFundTable/fundRow/FundRow.js
src/entries/components/flows/secondPillar/selectSources/pensionFundTable/fundRow/FundRow.spec.js

This means we don't have to mock the previously used `formatAmountForCurrency`, and it aligns better with how we use `retranslate`'s `Message`, which is also a component. It's also easy to test with `toEqual` or `containsMatchingElement`.

Create Euro component and use instead of formatter

---

src/entries/components/account/AccountStatement/AccountStatement.js
src/entries/components/account/AccountStatement/AccountStatement.spec.js
src/entries/components/common/api.js
src/entries/components/common/table/Table.js
src/entries/components/common/table/Table.spec.js
src/entries/components/translations/translations.en.json
src/entries/components/translations/translations.et.json

As the semantic tables in the repo are not responsive, we hide the contribution and profit columns on mobile.
For that, a new optional `hideOnMobile` flag is added to the `column` API.
Screenshot:

Add contribution and profit columns to account statements

---

package-lock.json
package.json
src/entries/components/common/http.js
src/entries/components/common/http.spec.js
src/entries/components/common/http.ts

Best read commit by commit.
This PR:
* makes http module use `async` and `await`
* makes http module TypeScript
* makes http.get use [axios](https://www.npmjs.com/package/axios)
No idea why the test coverage changes, everything is as covered as before.

Refactor http to use TypeScript and http.get to use Axios

---

src/entries/components/account/ReturnComparison/ReturnComparison.test.tsx
src/entries/components/account/ReturnComparison/ReturnComparison.tsx
src/entries/components/account/ReturnComparison/Select/Select.tsx
src/entries/components/account/ReturnComparison/api/returnComparison.api.test.ts
src/entries/components/account/ReturnComparison/api/returnComparison.api.ts

This PR:
* adds personal return select for II and III pillar
* adds disabled selects to prepare for other options to compare returns
* changes loader to not flicker the whole component

Add personal return select for II and III pillar

---

src/entries/components/translations/translations.et.json

Tuleva user sent a notification about a typo in the account summary heading. Fix conducted in the Estonian translation json file.

Fix account summary heading

---

src/entries/components/account/AccountSummary/AccountSummary.js
src/entries/components/account/AccountSummary/AccountSummary.spec.js
src/entries/components/common/table/Table.js
src/entries/components/common/table/Table.scss
src/entries/components/common/table/index.js
src/entries/components/common/utils.js

I noticed that at the moment a negative profit is displayed with green color, which is visually a bit misleading. I made a small code change that actually uses an existing method for identifying a profit color based on positive/negative number. I've attached screenshots to illustrate the situation now and my proposal:
Now: 
Proposed:
Maybe you want to use that :).

Indicate negative profit with red color

---

src/entries/components/flows/common/Flow.js

We upgraded react router, which changed the semantics of path matching on redirects. It wasn't a major version bump, which is why we missed it. It broke the `Flow` component, which we've now fixed by including an `exact` modifier on the redirect.

Fix flow redirects for new react router

---

src/entries/components/flows/secondPillar/success/Success.js
src/entries/components/flows/secondPillar/success/Success.spec.js

Upgrading a facebook client broke the page, as the Share button functions differently. After discussing with the team, we decided to instead remove the button as it isn't deemed useful.

Fix success screen

---

src/entries/components/flows/cancellation/ConfirmCancellation.tsx
src/entries/components/flows/cancellation/cancellationHooks.ts
src/entries/reducers.js

Adds two fixes to stale state:
- Checks that any signed mandate id matches the current application you are cancelling
- When logging out, removes all your state from redux

Add small redux fixes

---

src/components/exchange/reducer.js
src/components/exchange/reducer.spec.js

How to reproduce:
1. Add a bs invalid access token to your sessionStorage
2. Go straight to /account via url
2. Log in after it throws you to the login page
3. You'll see broken the validation message
Reason this was happening was that the exchange reducer error state comes in _after_ log out has happened and thus does not get reset. We're adding a reset for authentication success as well.

Fix validation message coming up after login

---

src/components/translations/translations.en.json
src/components/translations/translations.et.json

The previous button "Maksa" confused a lot of users - what does it actually do? Now we clarify we're showing the payment details in the next step.

Improve third pillar flow button clarity

---

src/components/contact-details/reducer.js
src/components/contact-details/reducer.spec.js
src/components/contact-details/updateUserForm/UpdateUserForm.js
src/components/contact-details/updateUserForm/UpdateUserForm.spec.js

This should add some clarity to people saying "the button does nothing" while the back-end might be slow.

Disable submit button when submitting contact details

---

src/components/common/api.ts
src/components/exchange/actions.js
src/components/exchange/actions.spec.js
src/components/flows/secondPillar/SecondPillarFlow.test.tsx
src/components/flows/secondPillar/confirmMandate/ConfirmMandate.js
src/components/flows/thirdPillar/ConfirmThirdPillarMandate/ConfirmThirdPillarMandate.js
src/test/backend.ts

Adds an event to record users that reach the confirmation page. We have a huge drop-off of users that don't sign the mandate so this will allow us to find these guys from the database later.
Partner PR to this fellow: https://github.com/TulevaEE/onboarding-service/pull/413

Add confirm page event

---

src/components/account/ApplicationSection/ApplicationCards.tsx
src/components/account/ApplicationSection/ApplicationSection.test.tsx
src/components/account/ApplicationSection/fixtures.ts
src/components/common/apiModels.ts

Currently we were never utilizing the cancellation deadline logic, since backend and frontend API's didnt match up. In the backend, cancellation deadline was added to the application details while frontend expected it on the toplevel.
Now we correctly hide the application cancellation button when deadline has passed.

Fix cancellation deadline API

---

src/components/flows/thirdPillar/ThirdPillarPayment/ThirdPillarPayment.js

This assures the users can see their pension account number without having to refresh the page when opening their third pillar account.
It's a true pain in the buttock to test useEffects with enzyme so this change isn't covered at the moment. I have a cunning plan to move towards react-testing-library based integration tests soon (tm), so it will be covered then.

Fetch updated user data when pension account number missing

---

src/components/account/statusBox/thirdPillarStatusBox/ThirdPillarStatusBox.test.tsx
src/components/account/statusBox/thirdPillarStatusBox/ThirdPillarStatusBox.tsx
src/components/account/statusBox/thirdPillarStatusBox/__snapshots__/ThirdPillarStatusBox.test.tsx.snap
src/components/thirdPillar/types.ts

We have customers who have transferred their third pillar to Tuleva and are not planning to add payments. They get worried when we're showing a red X mark with "your funds have not transferred yet", even though they are converted customers.

Show a green third pillar status when funds have been transferred

---

src/components/common/api.spec.js
src/components/common/api.ts
src/components/common/apiModels.ts
src/components/login/actions.js
src/components/login/actions.spec.js

To make the SmartID login process sessionless

Pass SmartID auth hash back to the API

---

src/components/login/loginForm/LoginForm.js

Show a more finger-friendly numeric keyboard instead of the alphanumeric one when focusing the "Identity code" field, both for Smart-ID and mID.

Show numeric keyboard when logging in

---

src/components/login/loginForm/LoginForm.js

Added autocomplete attributes so that field values could be saved into password managers and later easily filled.
Changed type attribute from 'number' to 'text' for ID code. Is more appropriate in this case and avoids input field with spinner buttons when styles fail to load. (The newly added inputmode attribute will continue to open the correct keyboard on mobile.)

Login fields’ attributes: added autocomplete, changed type

---

.eslintrc.js
src/components/LoggedInApp/LoggedInApp.js
src/components/account/GreetingBar/GreetingBar.js
src/components/common/utils.ts
src/components/flows/thirdPillar/ThirdPillarPayment/Payment.tsx
src/components/flows/thirdPillar/ThirdPillarPayment/ThirdPillarPaymentPage.tsx
src/components/flows/thirdPillar/ThirdPillarPayment/ThirdPillarPaymentStep.tsx
src/components/flows/thirdPillar/ThirdPillarPayment/paymentDetails/EmployerPaymentDetails.spec.tsx
src/components/flows/thirdPillar/ThirdPillarPayment/paymentDetails/EmployerPaymentDetails.tsx
src/components/translations/translations.en.json
src/components/translations/translations.et.json

Adds onboarding guide for direct employer 3rd pillar payments for public sector employees via Riigitöötaja Iseteenindusportaal.
Adds radio button to switch between private and public sector employees, with private selected by default. 
Covers the view with tests.
Minor changes:
* Turns off required return type rule to rely more on inferred types.
* Converts utils to typescript. 
* Adds util for full name getter.

Add onboarding guide for direct employer 3rd pillar payments, for public sector employees

---

src/components/account/ApplicationSection/ApplicationCards.tsx
src/components/account/ApplicationSection/DefinitionList.tsx
src/components/account/ComparisonCalculator/ComparisonCalculator.tsx
src/components/account/ComparisonCalculator/select/Select.tsx
src/components/account/ComparisonCalculator/types.ts
src/components/account/statusBox/statusBoxRow/StatusBoxRow.test.tsx
src/components/flows/secondPillar/selectSources/SelectSources.tsx
src/components/flows/secondPillar/selectSources/targetFundSelector/TargetFundSelector.tsx
src/components/flows/thirdPillar/ThirdPillarPayment/paymentDetails/OtherBankPaymentDetails.tsx
src/components/flows/thirdPillar/ThirdPillarPayment/paymentDetails/row/AccountNumberRow.tsx
src/components/translations/index.ts
src/global.d.ts

Improves translation key definition:
* Key has to be present in translation files.
* Key has to exist both in english and estonian.
Otherwise, typecheck fails. 
Uses [globals type definition override](https://stackoverflow.com/a/71963066) which isn't ideal, but was low effort.

Improve translation key type definition (has to be present both in EN and ET)

---

src/components/common/api.ts
src/components/common/http.ts
src/components/flows/thirdPillar/ThirdPillarPayment/BankButton.tsx
src/components/flows/thirdPillar/ThirdPillarPayment/Payment.tsx
src/components/flows/thirdPillar/ThirdPillarPayment/PaymentBankButtons.tsx
src/components/flows/thirdPillar/ThirdPillarPayment/PaymentSubmitSection.tsx
src/components/flows/thirdPillar/ThirdPillarPayment/PaymentTypeSelection.tsx
src/components/flows/thirdPillar/ThirdPillarPayment/RecurringPaymentDetails.tsx
src/components/flows/thirdPillar/ThirdPillarPayment/ThirdPillarGift.tsx
src/components/flows/thirdPillar/ThirdPillarPayment/types.ts
src/components/translations/translations.en.json
src/components/translations/translations.et.json

Adds error handling to 3rd pillar payment flow, as the link generation now includes an API call, it can now fail.
Refactors 3rd pillar payment section, splitting single big component to smaller ones.
Removes employer payment type for now, as it was dead code.

3rd pillar payment error handling & refactor

---

src/components/common/apiModels.ts
src/components/flows/secondPillar/SecondPillarFlow.test.tsx
src/components/flows/secondPillar/success/Success.tsx

If user just completed the II pillar flow, 
* and their current contribution rate is 2% 
* and they don't have a pending payment rate application
don't suggest increasing the payment rate.
Old state, when rate had already been increased
New state, when rate has already been increased

Check if user has II pillar payment rate application already done in II pillar flow, before suggesting increasing it

---

README.md
src/components/account/statusBox/thirdPillarStatusBox/ThirdPillarStatusBox.test.tsx
src/components/account/statusBox/thirdPillarStatusBox/ThirdPillarStatusBox.tsx
src/components/account/statusBox/thirdPillarStatusBox/__snapshots__/ThirdPillarStatusBox.test.tsx.snap
src/components/common/requestMocker/README.md
src/components/flows/secondPillar/selectSources/targetFundSelector/TargetFundSelector.spec.js

- fix a couple of typos in the project README
- document the clear/reset step in requestMocker README
- adjust ThirdPillarStatusBox logic to check active fund fee when balance is zero
- test the zero-balance fee case
- verify terms links in TargetFundSelector tests
- `npm run update-snapshot`

Fix typos and improve third pillar logic

---

src/components/LoggedInApp/LoggedInApp.js
src/components/flows/savingsAccount/SavingsFundPayment/SavingsFundPaymentSuccess.tsx
src/components/translations/translations.en.json
src/components/translations/translations.et.json

Adds a static success page that'll be used for the Montonio successful payment callbacks.

Add static savings fund payment success page
