TulevaEE/onboarding-client

src/steps/confirmMandate/ConfirmMandate.js
src/steps/confirmMandate/ConfirmMandate.spec.js
src/steps/confirmMandate/fundTransferMandate/FundTransferMandate.js
src/steps/confirmMandate/fundTransferMandate/FundTransferMandate.spec.js
src/steps/confirmMandate/fundTransferMandate/index.js

Extracts some components and adds tests

Refactor confirmation step

---

src/steps/confirmMandate/ConfirmMandate.scss

Also works across multiple lines now.

Simplify highlight

---

src/index.js
src/login/loginForm/LoginForm.js
src/termsOfUse/TermsOfUse.js
src/termsOfUse/TermsOfUse.spec.js
src/termsOfUse/index.js
src/translations/translations.et.json

Terms of use

---

src/account/AccountPage.js
src/account/index.js
src/index.js
src/steps/confirmMandate/ConfirmMandate.spec.js
src/translations/translations.et.json

Adds a basic skeleton for a page under /account

Basic account page

---

src/index.scss
src/steps/selectSources/targetFundSelector/TargetFundSelector.js
src/steps/selectSources/targetFundSelector/TargetFundSelector.scss

Style select target funds tiles

---

src/termsOfUse/TermsOfUse.js

On mobile, padding is missing without col.

Add column to terms of use for padding

---

src/common/authenticationLoader/AuthenticationLoader.scss
src/login/loginForm/LoginForm.js

- fix issue when auth loader window is small for a second
- fix responsive issue with login form on mobile

Login page styling

---

src/common/authenticationLoader/AuthenticationLoader.scss

Roling back my fix.
Just to bring things where they were. 
It will take more time to do the proper fix due to the way we use loader in different places (nested differently)
Pushing it live, in order to proceed with high prio stuff.
Will fix in the end of the day tomorrow.

Rollback fix

---

src/common/radio/Radio.js
src/common/radio/Radio.spec.js
src/steps/selectSources/exactFundSelector/fundExchangeRow/FundExchangeRow.scss
src/steps/selectSources/targetFundSelector/TargetFundSelector.js

Simple little responsive and cross-browser fixes.

Safari and ios fixes

---

src/steps/success/Success.js
src/steps/success/Success.spec.js
src/translations/translations.et.json

- Only show info about the fund when it was previously selected 
- Add button to profile

Success step improvement

---

src/steps/selectSources/pensionFundTable/PensionFundTable.js
src/steps/selectSources/pensionFundTable/PensionFundTable.spec.js
src/steps/selectSources/pensionFundTable/fundRow/FundRow.js
src/steps/selectSources/pensionFundTable/fundRow/FundRow.spec.js
src/translations/translations.et.json

Shows a little * next to the name.

Add showing active fund in flow

---

src/index.scss
src/steps/transferFutureCapital/TransferFutureCapital.js
src/steps/transferFutureCapital/TransferFutureCapital.spec.js
src/translations/translations.en.json
src/translations/translations.et.json

Active fund note 2nd step

---

src/index.js
src/login/actions.js

Make it track the user id, and the release commit.

Add further raven context

---

src/entries/components/account/AccountPage.js
src/entries/components/account/updateUserForm/UpdateUserForm.js
src/entries/components/translations/translations.et.json

Move user details update block

---

.eslintrc
package-lock.json
package.json
src/entries/components/_variables.scss
src/entries/components/account/AccountPage.js
src/entries/components/account/AccountPage.spec.js
src/entries/components/common/api.js
src/entries/components/common/api.spec.js
src/entries/components/index.scss
src/entries/components/returnComparison/ReturnComparison.js
src/entries/components/returnComparison/ReturnComparison.spec.js
src/entries/components/returnComparison/actions.js
src/entries/components/returnComparison/actions.spec.js
src/entries/components/returnComparison/constants.js
src/entries/components/returnComparison/index.js
src/entries/components/returnComparison/reducer.js
src/entries/components/returnComparison/reducer.spec.js
src/entries/components/translations/translations.en.json
src/entries/components/translations/translations.et.json
src/entries/onboarding.js
src/test/utils.js

Add return comparison

---

src/entries/components/returnComparison/actions.js
src/entries/components/returnComparison/actions.spec.js

*ReturnPercentage -> *AverageReturnPercentage

Fix the typo in prop names

---

__mocks__/retranslate.js
package-lock.json
package.json
src/entries/components/account/AccountPage.js
src/entries/components/account/AccountPage.spec.js
src/entries/components/account/Select/Select.js
src/entries/components/account/Select/Select.spec.js
src/entries/components/account/Select/index.js
src/entries/components/common/api.js
src/entries/components/common/api.spec.js
src/entries/components/returnComparison/ReturnComparison.js
src/entries/components/returnComparison/ReturnComparison.spec.js
src/entries/components/returnComparison/actions.js
src/entries/components/returnComparison/actions.spec.js
src/entries/components/returnComparison/options.js
src/entries/components/returnComparison/options.spec.js
src/entries/components/translations/translations.en.json
src/entries/components/translations/translations.et.json
src/entries/onboarding.js

Add return comparison start date changing (and explanation link)

---

src/entries/components/account/AccountPage.js
src/entries/components/account/AccountPage.spec.js
src/entries/onboarding.js

This enables return comparison for everyone 🚀

Remove return comparison feature check

---

src/entries/components/account/AccountPage.js

Replace old link for non-members sign-up

Update become a member link

---

src/entries/components/returnComparison/options.js
src/entries/components/returnComparison/options.spec.js
src/entries/components/translations/translations.en.json
src/entries/components/translations/translations.et.json

add 10 year IRR calculation and corresponding labels and testst

10 year irr

---

src/entries/components/config/config.js
src/entries/components/translations/translations.en.json
src/entries/components/translations/translations.et.json

needs to be merged at 01.April 00:00

amount 100 -> 125

---

src/entries/components/returnComparison/options.js
src/entries/components/returnComparison/options.spec.js
src/entries/components/translations/translations.en.json
src/entries/components/translations/translations.et.json

Let`s add for our 2nd anniversary also 2 -year IRR...

2 year irr

---

.circleci/config.yml

This should resolve the out of memory error:
Origin of solution [here](https://discuss.circleci.com/t/babel-7-jest-results-in-timeout/25383).

Attempt to fix CircleCI Jest memory issue

---

src/entries/PrivateRoute/PrivateRoute.js
src/entries/PrivateRoute/index.js
src/entries/components/flows/thirdPillar/ConfirmThirdPillarMandate/ConfirmThirdPillarMandate.js
src/entries/components/flows/thirdPillar/ConfirmThirdPillarMandate/ConfirmThirdPillarMandate.spec.js
src/entries/components/login/LoginPage.js
src/entries/components/login/actions.js
src/entries/components/login/actions.spec.js
src/entries/components/router/actions.js
src/entries/onboarding.js

Just pushing my progress, as @ErkoRisthein inquired about this and I had worked on it a few weeks ago.
This PR creates a `PrivateRoute` component that redirects to login when not authenticated, and upon authentication redirects back to the requested page, allowing us to link straight to 2nd or 3rd pillar flow with optional authentication.
TODO:
* add tests
* delete `requireAuthentication`
* QA to ensure everything still works as expected

[WIP] Add PrivateRoute with redirect to wanted path

---

src/entries/components/account/FundDetailsTable/FundDetailsTable.js
src/entries/components/account/FundsOverviewTable/FundsOverviewTable.js
src/entries/components/account/MemberCapital/MemberCapital.js
src/entries/components/account/MemberCapital/MemberCapital.spec.js
src/entries/components/common/table/LegacyTable.js
src/entries/components/common/table/Table.js
src/entries/components/common/table/Table.spec.js
src/entries/components/common/table/index.js

Reusable `Table` component, with an API inspired by the commonly used [Ant Design Table](https://ant.design/components/table/).

Create Table component

---

__mocks__/retranslate.js
src/entries/components/account/AccountPage.js
src/entries/components/account/FundDetailsTable/FundDetailsTable.js
src/entries/components/account/statusBox/StatusBox.js
src/entries/components/flows/common/Flow.js
src/entries/components/flows/thirdPillar/ConfirmThirdPillarMandate/ConfirmThirdPillarMandate.js
src/entries/components/flows/thirdPillar/ConfirmThirdPillarMandate/ThirdPillarTermsAgreement/ThirdPillarTermsAgreement.js
src/entries/components/flows/thirdPillar/ThirdPillarAddress/ThirdPillarAddress.js
src/entries/components/flows/thirdPillar/ThirdPillarPayment/ThirdPillarPayment.js
src/entries/components/login/loginForm/LoginForm.js

Information on short syntax [here](https://reactjs.org/docs/fragments.html#short-syntax).
Support was added in [Babel 7](https://babeljs.io/blog/2018/08/27/7.0.0#jsx-fragment-support).

Replace Fragment with short syntax

---

src/entries/components/account/AccountStatement/AccountStatement.js
src/entries/components/account/AccountStatement/AccountStatement.spec.js

This data is not a sum of the values in the column, so we decided to remove.

Remove total contribution and profit

---

src/entries/components/account/AccountStatement/AccountStatement.js
src/entries/components/account/AccountStatement/AccountStatement.spec.js
src/entries/components/common/Percentage/Percentage.test.tsx
src/entries/components/common/Percentage/Percentage.tsx
src/entries/components/common/Percentage/index.ts
src/entries/components/common/api.js
src/entries/components/common/api.spec.js
src/entries/components/translations/translations.en.json
src/entries/components/translations/translations.et.json

This PR:
* passes ongoing charges figure through fund transformation
* adds `Percentage` component
* adds fund fees to account statement
Screenshot:

Add fund fees to account statement

---

src/entries/components/common/api.js
src/entries/components/common/api.ts

**Best read commit by commit, otherwise it shows the changes as a completely new file.**

Refactor API to use async/await and TypeScript

---

src/entries/components/account/ApplicationSection/ApplicationCards.tsx
src/entries/components/account/ApplicationSection/ApplicationSection.test.tsx
src/entries/components/common/apiModels.ts

Parses cancellation deadline as YYYY-MM-DD and checks that the current day is the same or before when showing the cancellation button.

Add cancellation deadline

---

.circleci/config.yml
__mocks__/retranslate.js
src/components/account/statusBox/StatusBox.test.tsx
src/components/flows/cancellation/CancellationFlow.test.tsx
src/components/login/LoginPage.js
src/components/login/LoginPage.test.tsx
src/components/login/loginForm/LoginForm.js
src/components/login/loginForm/LoginTabs.js
src/entries/components/login/LoginPage.test.tsx
src/index.js
src/test/utils.tsx

Login tests will be done in next pr. Adding initial refactoring to move to using messages rather than labels for rtl tests.

Move new tests to unmock retranslate and start login tests

---

src/components/flows/secondPillar/SecondPillarFlow.test.tsx
src/test/backend.ts

We want to gain more confidence when making changes and therefore want to add integration tests to the most important flows.

Add 2nd pillar happy flow test

---

src/components/LoggedInApp/LoggedInApp.js
src/components/account/AccountPage.js
src/components/account/AccountPage.spec.js
src/components/account/AccountPageView.test.tsx
src/components/account/AccountSummary/AccountSummary.js
src/components/account/GreetingBar/GreetingBar.js
src/components/account/statusBox/StatusBox.tsx
src/components/common/shimmer/Shimmer.module.scss
src/components/common/shimmer/Shimmer.tsx

Add better loading states to the entire application.
Done in a hurry and should be cleaned up, but should make above the flow loading much less janky.

Better loading state

---

src/components/translations/translations.en.json
src/components/translations/translations.et.json

Please accept at midnight 31. july

Tonupekk change dates

---

src/components/account/ApplicationSection/ApplicationCards.tsx
src/components/account/ApplicationSection/ApplicationSection.test.tsx
src/components/common/Percentage/Percentage.test.tsx
src/components/common/Percentage/Percentage.tsx

Show third pillar transfer amounts in correct units

---

package.json
src/components/account/AccountStatement/AccountStatement.js
src/components/account/statusBox/StatusBox.test.tsx
src/components/common/apiModels.ts
src/components/thirdPillar/reducer.js
src/components/thirdPillar/reducer.spec.js
src/components/translations/translations.en.json

A partner to this PR: https://github.com/TulevaEE/onboarding-service/pull/385

Show zero value third pillar funds

---

src/components/account/statusBox/StatusBox.tsx

Fix a visual bug that happened during refactoring

Re-add second pillar status box title

---

src/components/account/statusBox/StatusBox.tsx
src/components/account/statusBox/__snapshots__/StatusBox.test.tsx.snap
src/components/account/statusBox/thirdPillarStatusBox/ThirdPillarStatusBox.tsx
src/components/account/statusBox/thirdPillarStatusBox/__snapshots__/ThirdPillarStatusBox.test.tsx.snap
src/components/translations/translations.en.json
src/components/translations/translations.et.json

They can now be found in your third pillar status box like so:

Move third pillar contributions to a more visible location

---

src/components/account/statusBox/thirdPillarStatusBox/ThirdPillarStatusBox.tsx
src/components/account/statusBox/thirdPillarStatusBox/__snapshots__/ThirdPillarStatusBox.test.tsx.snap
src/components/translations/translations.en.json
src/components/translations/translations.et.json

Add tooltip to help users figure out when their funds reach Tuleva

---

src/components/account/AccountStatement/AccountStatement.js
src/components/account/AccountSummary/AccountSummary.js
src/components/account/AccountSummary/AccountSummary.spec.js
src/components/account/ApplicationSection/ApplicationCards.tsx
src/components/account/ApplicationSection/ApplicationSection.test.tsx
src/components/account/ApplicationSection/ApplicationSection.tsx
src/components/account/ApplicationSection/DefinitionList.tsx
src/components/contact-details/ContactDetailsPage.js
src/components/contact-details/updateUserForm/UpdateUserForm.js
src/components/contact-details/updateUserForm/UpdateUserForm.spec.js

The next step to the process started in [here](https://github.com/TulevaEE/onboarding-client/pull/871).

Continue moving towards react-intl

---

src/components/account/statusBox/thirdPillarStatusBox/ThirdPillarStatusBox.test.tsx
src/components/account/statusBox/thirdPillarStatusBox/ThirdPillarStatusBox.tsx

If there are payments then contribution total is not 0.

Remove redundant payment check

---

src/components/account/ApplicationSection/ApplicationCards.tsx
src/components/account/ApplicationSection/ApplicationSection.test.tsx

It's not possible to cancel third pillar transfers in Pensionikeskus and will result in an error

Don't allow cancellation of third pillar transfers

---

src/components/account/ReturnComparison/ReturnComparison.test.tsx
src/components/account/ReturnComparison/ReturnComparison.tsx
src/components/account/ReturnComparison/api/returnComparison.api.test.ts
src/components/account/ReturnComparison/api/returnComparison.api.ts
src/components/translations/translations.en.json
src/components/translations/translations.et.json

Adds return on investment calculator that displays cash amounts

Adds return on investment calculatior as cash amounts

---

.gitignore
src/components/_variables.scss
src/components/account/SecondPillarUpsell/SecondPillarUpsell.scss
src/components/account/statusBox/statusBoxRow/StatusBoxRow.scss
src/components/flows/common/Flow.scss
src/components/flows/common/Notice/Notice.module.scss
src/components/flows/common/StepTitle/StepTitle.scss
src/components/flows/secondPillar/confirmMandate/fundTransferTable/FundTransferTable.scss
src/components/flows/secondPillar/selectSources/exactFundSelector/fundExchangeRow/FundExchangeRow.scss
src/components/flows/secondPillar/selectSources/targetFundSelector/TargetFundSelector.scss
src/components/flows/thirdPillar/ThirdPillarPayment/ThirdPillarPayment.scss
src/components/flows/thirdPillar/ThirdPillarSuccess/ThirdPillarSuccess.module.scss
src/components/fonts/index.scss
src/components/login/LoginPage.scss
src/components/login/loginForm/LoginForm.scss

- style: autoformat src/
- chore: ignore test-results.json

style: autoformat src/

---

.eslintrc.js
src/components/account/AccountPage.js
src/components/account/SectionHeading.tsx
src/components/translations/index.ts

Removes breakpoint and makes `flex-direction: row` the default for all screen sizes.

Refactor section heading to component, translations to TS

---

src/components/common/ScrollToTopOnNavigation.tsx
src/index.jsx

Before
https://github.com/TulevaEE/onboarding-client/assets/3755903/b26ce467-60be-46e1-bf18-51ec6a16dec1
After
https://github.com/TulevaEE/onboarding-client/assets/3755903/252786ea-6c3c-49b0-9bec-e4af41195aee

Scroll to top after navigation

---

package-lock.json
package.json
src/@types/global.d.ts
src/@types/hwcrypto-js.d.ts
src/components/account/ComparisonCalculator/types.ts
src/components/exchange/actions.ts
src/global.d.ts

Rough reverse engineering conversion of exchange actions (mainly signing logic) to TS.

Convert exchange actions to TS

---

src/components/account/ApplicationSection/ApplicationCards.tsx
src/components/account/ApplicationSection/ApplicationSection.test.tsx
src/components/account/ApplicationSection/fixtures.ts
src/components/common/apiModels/index.ts
src/components/translations/translations.en.json
src/components/translations/translations.et.json

Add withdrawal applications to account view

---

src/components/common/apiModels/withdrawals.ts
src/components/common/radio/Radio.js
src/components/common/radio/Radio.scss
src/components/flows/withdrawals/ReviewAndConfirmStep.tsx
src/components/flows/withdrawals/WithdrawalAmountStep.tsx
src/components/flows/withdrawals/Withdrawals.module.scss
src/components/flows/withdrawals/WithdrawalsFlow.test.tsx
src/components/flows/withdrawals/WithdrawalsHeader.tsx
src/components/flows/withdrawals/fixture.ts
src/components/flows/withdrawals/hooks.tsx
src/components/flows/withdrawals/utils.spec.ts
src/components/flows/withdrawals/utils.ts
src/components/translations/translations.en.json
src/components/translations/translations.et.json
src/test/backend.ts

Applies to those who opened at least 5 years ago and before 2021:

Add logic for early III pillar withdrawal for over 55s

---

src/components/account/AccountPage.js
src/components/account/AccountPageView.test.tsx
src/components/account/AccountSummary/AccountSummary.js
src/components/account/ComparisonCalculator/select/Select.tsx
src/components/account/statusBox/ActiveFundPensionDescription.tsx
src/components/account/statusBox/secondPillarStatusBox/SecondPillarStatusBox.test.tsx
src/components/account/statusBox/secondPillarStatusBox/SecondPillarStatusBox.tsx
src/components/account/statusBox/statusBoxRow/StatusBoxRow.scss
src/components/account/statusBox/statusBoxRow/StatusBoxRow.tsx
src/components/account/statusBox/thirdPillarStatusBox/ThirdPillarStatusBox.test.tsx
src/components/account/statusBox/thirdPillarStatusBox/ThirdPillarStatusBox.tsx
src/components/account/statusBox/utils.ts
src/components/common/api.test.ts
src/components/common/api.ts
src/components/common/apiHooks.ts
src/components/common/apiModels/index.ts
src/components/common/apiModels/withdrawals.ts
src/components/flows/secondPillar/confirmMandate/fundTransferTable/FundTransferTable.scss
src/components/flows/withdrawals/ReviewAndConfirmStep.tsx
src/components/flows/withdrawals/WithdrawalsFlow.test.tsx
src/components/translations/translations.en.json
src/components/translations/translations.et.json
src/test/backend-responses.ts
src/test/backend.ts

Add fund pension info to statusbox

---

README.md
src/components/LoggedInApp/header/languageSwitcher/LanguageSwitcher.test.tsx
src/components/account/statusBox/statusBoxRow/StatusBoxRow.tsx
src/polyfills.js

- remove `String.prototype.startsWith` polyfill
- `npm test` *(fails: No tests found related to files changed since last commit)*

Remove startsWith polyfill
